apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: feedforge
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: feedforge
data:
  BACKUP_BUCKET: feedforge-db-backup-project-76da2d1f-231c-4c94-ae9
  PGHOST: cloudsql-proxy
  PGDATABASE: feedforge
