apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: feedforge
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: queue
    app.kubernetes.io/part-of: feedforge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
