apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: backend-armor
  namespace: feedforge
  labels:
    app.kubernetes.io/name: backend-armor
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: feedforge
spec:
  default:
    securityPolicy: feedforge-allow-ip
  targetRef:
    group: ""
    kind: Service
    name: backend
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: frontend-armor
  namespace: feedforge
  labels:
    app.kubernetes.io/name: frontend-armor
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: feedforge
spec:
  default:
    securityPolicy: feedforge-allow-ip
  targetRef:
    group: ""
    kind: Service
    name: frontend
