apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup
  namespace: feedforge
  annotations:
    iam.gke.io/gcp-service-account: feedforge-db-backup@project-76da2d1f-231c-4c94-ae9.iam.gserviceaccount.com
