apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/project-76da2d1f-231c-4c94-ae9/feedforge/backend
    newTag: a42276a
  - name: us-central1-docker.pkg.dev/project-76da2d1f-231c-4c94-ae9/feedforge/frontend
    newTag: a42276a

patches:
  - path: patches/backend-config-patch.yaml
  - path: patches/summarizer-sa-patch.yaml
  - path: patches/backend-sa-patch.yaml
  - path: patches/fetcher-sa-patch.yaml
  - path: patches/digest-sa-patch.yaml
  - path: patches/backup-sa-patch.yaml
  - path: patches/spc-postgres-patch.yaml
  - path: patches/spc-notification-patch.yaml
