apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/backend-config-patch.yaml
  - path: patches/summarizer-sa-patch.yaml
  - path: patches/backend-sa-patch.yaml
  - path: patches/fetcher-sa-patch.yaml
  - path: patches/digest-sa-patch.yaml
  - path: patches/backup-sa-patch.yaml
  - path: patches/postgres-sa-patch.yaml
